In [1]:
from wrapR import R
import numpy as np
import pandas as pd

# Initialize the wrapR
r = R()

## You can execute code

In [2]:
r('print(10)')

[1] 10


array([10.])

## You can `push` values to R and `get` values from R

In [10]:
r.push(D=np.array([0,1,2,3,56,8]))
X = r.get('D')

### When you execute code, the result of your code is also returned automatically

In [13]:
M = r('M <- E + diag(1, dim(E))', push=dict(E=np.zeros((10,10))))
M

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## If you run a line of code that doesn't work, you are told about it

In [5]:
r('library(lmerTest)')

R[write to console]: Error in library(lmerTest) : there is no package called ‘lmerTest’
Calls: <Anonymous> -> <Anonymous> -> library



Error in library(lmerTest) : there is no package called ‘lmerTest’
Calls: <Anonymous> -> <Anonymous> -> library



## You can run multiple lines of code

In [6]:
summary = r("""
    D <- c(rnorm(100,10,1), rnorm(100,1,1))
    E <- c(rep('0',100), rep('1',100))

    fit <- lm(D~E)
    S <- summary(fit)
    print(S)
    S
    """)


Call:
lm(formula = D ~ E)

Residuals:
     Min       1Q   Median       3Q      Max 
-3.01768 -0.62564  0.06152  0.63401  2.75722 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   9.8905     0.1055   93.72   <2e-16 ***
E1           -8.9598     0.1492  -60.04   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.055 on 198 degrees of freedom
Multiple R-squared:  0.9479,	Adjusted R-squared:  0.9477 
F-statistic:  3604 on 1 and 198 DF,  p-value: < 2.2e-16



In [7]:
summary['coefficients']

array([[ 9.89050366e+000,  1.05528422e-001,  9.37236008e+001,
         5.53642938e-166],
       [-8.95979321e+000,  1.49239725e-001, -6.00362484e+001,
         5.11960735e-129]])

In [8]:
r('S$coefficients')

array([[ 9.89050366e+000,  1.05528422e-001,  9.37236008e+001,
         5.53642938e-166],
       [-8.95979321e+000,  1.49239725e-001, -6.00362484e+001,
         5.11960735e-129]])

In [9]:
D = pd.DataFrame([[10,20],[30,40]], columns=['first','second'])
Y = r('Y <- D*2', push=dict(D=D), get='Y')
Y

first  second
0   20.0    40.0
1   60.0    80.0

In [3]:
r.push(D={'x':dict(k=np.array([100]))})
r('print(D)')

r('D')

$x
$x$k
[1] 100




{'x': {'k': array([100], dtype=int32)}}